---
name: "Build all packages"
description: "Composite action to build all included Arch Linux packages"

runs:
  using: "composite"
  steps:
    - name: "Build"
      shell: "bash"
      run: |
        # change workspace ownership
        chown -R $BUILDER_USER $GITHUB_WORKSPACE

        runuser --user $BUILDER_USER make build
...
