---
name: "Build and release new Arch Linux repository"

on:
  push:
    branches: ["master", "ci"]
  # allow to trigger workflow manually
  workflow_dispatch:

permissions:
  contents: "write"

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "archlinux:base-devel"
    steps:
      - uses: "actions/checkout@v7.0.0"

      - name: "Build all packages"
        uses: ".github/actions/build-all-packages"

      - name: "Update repository"
        run: "make update-repo"

      # GitHub requires presence of tag for release
      # this action will automatically create/update `latest` tag for usage in release later on
      - name: "Update latest tag"
        uses: "EndBug/latest-tag@v1.6.3"

      - name: "Update latest GitHub release"
        uses: "softprops/action-gh-release@v3.0.1"
        with:
          name: "Latest"
          draft: true
          files: "build/*"
          overwrite_files: true
          # make_latest: true
...
