---
name: "Build PR"

on:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "ghcr.io/dikoval/arch-repo-builder:latest"
    steps:
      - uses: "actions/checkout@v7.0.0"
        with:
          submodules: "recursive"

      - name: "Lint all packages"
        run: "make lint"
        continue-on-error: true

      - name: "Build"
        run: |
          # use $BUILDER_USER from base container
          chown -R $BUILDER_USER $GITHUB_WORKSPACE

          runuser --user $BUILDER_USER make build
...
