---
name: "Build PR"

on:
  pull_request:
  # allow to trigger workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    # container: "archlinux:base-devel"
    steps:
      - name: "Install dependencies"
        run: |
          sudo pacman -Sy --needed --noconfirm git make

      - uses: "actions/checkout@v7.0.0"
        with:
          submodules: "recursive"

      - name: "Create non-root user"
        run: |
          useradd not-root
          # Allow build to run stuff as root (to install dependencies):
          echo "not-root ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/not-root
          # change file ownership
          chown -R not-root .

      #- name: "Sync submodules"
      #  run: "make sync"

      - name: "Build"
        run: "runuser -u not-root make build"
...
