---
name: "Build and release"

on:
  push:
    branches: ["master"]
  # allow to trigger workflow manually
  workflow_dispatch:

permissions:
  contents: "write"

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "ghcr.io/dikoval/arch-repo-builder:latest"
    steps:
      - uses: "actions/checkout@v7.0.0"
        with:
          submodules: "recursive"

      - name: "Build"
        run: |
          # use $BUILDER_USER from base container
          chown -R $BUILDER_USER $GITHUB_WORKSPACE

          runuser --user $BUILDER_USER make build

      - name: "Update repository"
        run: "make update-repo"

      - name: "Record build date and time"
        run: |
          echo "DATE=$(date --utc --iso-8601=date)" >> $GITHUB_ENV
          echo "DATE_TIME=$(date --utc --iso-8601=seconds)" >> $GITHUB_ENV

      # GitHub requires presence of tag for release
      # this action will automatically create/update `latest` tag for usage in release later on
      - name: "Update latest tag"
        uses: "richardsimko/update-tag@v2.0.0"
        with:
          tag_name: "latest"

      - name: "Update latest GitHub release"
        uses: "softprops/action-gh-release@v3.0.1"
        with:
          name: "Latest - ${{ env.DATE }}"
          body: "Built on ${{ env.DATE_TIME }}"
          tag_name: "latest"
          files: "build/*"
          overwrite_files: true
          make_latest: true
...
