---
name: "Build PR"

on:
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "archlinux:base-devel"
    steps:
      - name: "Install dependencies"
        run: |
          # git is required to sync submodules with both `checkout` action and `make sync`
          pacman -Sy --needed --noconfirm git namcap

      - uses: "actions/checkout@v7.0.0"
        with:
          submodules: "recursive"

      - name: "Lint all packages"
        run: "make lint"
        continue-on-error: true

      - name: "Build all packages"
        uses: "./.github/actions/build-all-packages"
...
